"""initial schema

Revision ID: 84515ff89142
Revises: 
Create Date: 2026-07-18 11:39:13.521929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84515ff89142'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_retenido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nota_retencion', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('RECIBO_FIJO', 'VARIABLE', 'ANUAL', 'PUNTUAL', 'INGRESO', name='tipocategoria'), nullable=False),
    sa.Column('grupo', sa.Enum('NECESIDAD', 'DESEO', 'PUNTUAL', 'INGRESO', name='grupocategoria'), nullable=False),
    sa.Column('dia_cargo', sa.Integer(), nullable=True),
    sa.Column('presupuesto_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('es_apoyo_suegros', sa.Boolean(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('meta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ahorrado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_objetivo', sa.Date(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_ts'), 'login_attempts', ['ts'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('net_worth_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('ACTIVO', 'PASIVO', name='tipopatrimonio'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('settings',
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('suegros_support_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meses_previstos', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('annual_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('importe_anual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mes_cargo', sa.Integer(), nullable=True),
    sa.Column('compania', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nomina_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('num_pagas', sa.Integer(), nullable=False),
    sa.Column('pct_a_comun', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('meses_pagas_extra', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('net_worth_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['net_worth_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'anio', 'mes', name='uq_net_worth_item_periodo')
    )
    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('GASTO', 'INGRESO_NOMINA', 'INGRESO_EXTRA', name='tipomovimiento'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pagado_con', sa.Enum('CUENTA_COMUN', 'JULIO_PERSONAL', 'YANAY_PERSONAL', name='pagadocon'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_fecha'), 'transactions', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_fecha'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('recovery_codes')
    op.drop_table('net_worth_entries')
    op.drop_table('income_profiles')
    op.drop_table('annual_expenses')
    op.drop_table('users')
    op.drop_table('suegros_support_config')
    op.drop_table('settings')
    op.drop_table('net_worth_items')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ts'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('goals')
    op.drop_table('categories')
    op.drop_table('balance_snapshots')
    # ### end Alembic commands ###
