"""login_attempts kind + mfa settings

Revision ID: e9c4aead1627
Revises: 84515ff89142
Create Date: 2026-07-19 00:07:06.737161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c4aead1627'
down_revision: Union[str, Sequence[str], None] = '84515ff89142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_attempts', sa.Column('kind', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_attempts', 'kind')
    # ### end Alembic commands ###
